services:
  bot:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - app/.env.prod
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://user:pass@postgres:5432/anti_drugs_db?schema=public"

  postgres:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: anti_drugs_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d anti_drugs_db" ]
      interval: 3s
      timeout: 3s
      retries: 10
  redis:
    command: redis-server --requirepass pass
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          memory: 512M
