services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: anti-drugs-bot
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - botnet

  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: anti-drugs-db
    environment:
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - botnet

  redis:
    image: redis:7-alpine
    container_name: anti-drugs-redis
    environment:
      TZ: Europe/Moscow
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    volumes:
      - redisdata:/data
    networks:
      - botnet

networks:
  botnet:

volumes:
  pgdata:
  redisdata:
