services:
  bot:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://user:pass@postgres:5432/anti_drugs_db?schema=public"
    volumes:
      - ./app:/app

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: anti_drugs_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 3s
      timeout: 3s
      retries: 10
